### ISSUE TITLE
error running plugins: timed out waiting for plugins, shutting down HTTP server

### ISSUE THREAD

**Issue by stewart-yu** [heptio/sonobuoy#118]
[root@test-fp-node-2 result]# cat meta/run.log 
{"level":"info","msg":"Namespace default Matched=true","time":"2017-10-16T14:27:49Z"}
{"level":"info","msg":"Namespace kube-public Matched=true","time":"2017-10-16T14:27:49Z"}
{"level":"info","msg":"Namespace kube-system Matched=true","time":"2017-10-16T14:27:49Z"}
{"level":"info","msg":"Namespace sonobuoy Matched=true","time":"2017-10-16T14:27:49Z"}
{"level":"info","msg":"Starting server Expected Results: [{ e2e}]","time":"2017-10-16T14:27:49Z"}
{"level":"info","msg":"Running (e2e) plugin","time":"2017-10-16T14:27:49Z"}
{"level":"info","msg":"Listening for incoming results on 0.0.0.0:8080\n","time":"2017-10-16T14:27:49Z"}
{"level":"error","msg":"error running plugins: timed out waiting for plugins, shutting down HTTP server","time":"2017-10-16T15:27:49Z"}
{"level":"info","msg":"Running non-ns query","time":"2017-10-16T15:27:49Z"}
{"level":"info","msg":"Running ns query (default)","time":"2017-10-16T15:27:49Z"}
{"level":"info","msg":"Running ns query (kube-public)","time":"2017-10-16T15:27:49Z"}
{"level":"info","msg":"Running ns query (kube-system)","time":"2017-10-16T15:27:49Z"}
{"level":"info","msg":"Running ns query (sonobuoy)","time":"2017-10-16T15:27:49Z"}

Why plugins time out? But run only one testcase instead of all Conformance don't.

**Comment by timothysc** [comment]
To be certain you would have to look at the e2e container logs which would should detail what happened.  The most common case we've see is something blocking connectivity from the e2e pod to the sonobuoy master.    

We have an issue open to default to always collect pod logs for the sonobuoy namespace, and I'll shift that one to p1 or p0.

**Comment by timothysc** [comment]
Closing this one in favor of - https://github.com/heptio/sonobuoy/issues/81 where the work will occur.

**Comment by wjx1995** [comment]
{"level":"info","msg":"Namespace default Matched=true","time":"2017-12-01T06:04:00Z"}
{"level":"info","msg":"Namespace e2e-tests-emptydir-rm56f Matched=true","time":"2017-12-01T06:04:00Z"}
{"level":"info","msg":"Namespace e2e-tests-projected-9vl2l Matched=true","time":"2017-12-01T06:04:00Z"}
{"level":"info","msg":"Namespace ekos-plugin Matched=true","time":"2017-12-01T06:04:00Z"}
{"level":"info","msg":"Namespace kube-public Matched=true","time":"2017-12-01T06:04:00Z"}
{"level":"info","msg":"Namespace kube-system Matched=true","time":"2017-12-01T06:04:00Z"}
{"level":"info","msg":"Starting server Expected Results: [{ e2e}]","time":"2017-12-01T06:04:00Z"}
{"level":"info","msg":"Running (e2e) plugin","time":"2017-12-01T06:04:00Z"}
{"level":"info","msg":"Listening for incoming results on 0.0.0.0:8080\n","time":"2017-12-01T06:04:00Z"}
{"level":"error","msg":"error running plugins: timed out waiting for plugins, shutting down HTTP server","time":"2017-12-01T07:34:00Z"}
{"level":"info","msg":"Running non-ns query","time":"2017-12-01T07:34:00Z"}
{"level":"info","msg":"Running ns query (default)","time":"2017-12-01T07:34:00Z"}
{"level":"info","msg":"Running ns query (e2e-tests-emptydir-rm56f)","time":"2017-12-01T07:34:00Z"}
{"level":"info","msg":"Running ns query (e2e-tests-projected-9vl2l)","time":"2017-12-01T07:34:00Z"}
{"level":"info","msg":"Running ns query (ekos-plugin)","time":"2017-12-01T07:34:00Z"}
{"level":"info","msg":"Running ns query (kube-public)","time":"2017-12-01T07:34:00Z"}
{"level":"info","msg":"Running ns query (kube-system)","time":"2017-12-01T07:34:00Z"}
Why plugins time out? But run only one testcase instead of all Conformance don't

**Comment by timothysc** [comment]
@wjx1995 it depends on what you are submitting.  

If you run 
``` kubectl apply -f https://raw.githubusercontent.com/heptio/sonobuoy/master/examples/conformance.yaml ``` 

It will run the conformance tests and collect the logs if it wedges.
