### ISSUE TITLE
Provide ppc64le binary and image

### ISSUE THREAD

**Issue by MatthieuSarter** [heptio/sonobuoy#1454]
It would be great to have official binary and image for ppc64le.

I have the required change for the build script, it builds fine. Tests (stress) are running OK and I also did some real usage test, with Kata's integration tests that are using Sonobuoy.

**Comment by barthy1** [comment]
> In general, I think you can make a good case that we should support all the versions that k8s does. That would mean we may want to consider (ppc64le, s390x, arm [we build arm64]).

I'd love to work on addition of `linux/s390x` build to sonobuoy. 
So far I've executed the stress and integration tests on s390x. In general things look good except failing some integration test, because `sonobuoy/systemd-logs:v0.3` image is missing for s390x. I see that for other platforms it was built 2 years ago just 1 time (I guess manually?). Would it be possible to build the `sonobuoy/systemd-logs` image for s390x and add it to multi-arch version as well?

**Comment by barthy1** [comment]
> I didn't think any of the integration tests required the systemd-logs; and even then we can build the binary/image without having explicit integration testing on it. We talked about this in a recent Sonobuoy status meeting and mentioned that for some of the less common arches like ppc64le and s390x we can just edit the README or docs to mention that those are community supported for testing/feedback rather than being tied into our CI at the time.

Yeah, I didn't suggest to extend your CI system to run the tests for new platforms. Just tried to verify from my side, that `sonobuoy` binary is workable for `linux/s390x` platform.

> I can put it on my list to build/release systemd-logs for those arches; do you have a recommendation for the base image or anything else I need to know about ppc64le or s390x?

I've submitted the PR to add `s390x` to systemd-logs image build. btw `ppc64le` was already there :)
I've also tested that systemd-logs build works ok with new architecture and reexecuted the sonobuoy integration tests with newly built systemd-logs image on s390x. Now all tests are passed.
