### ISSUE TITLE
Scan runs >1 hr, then error occurs and all results are lost

### ISSUE THREAD

**Issue by rdodev** [heptio/sonobuoy#214]
Environment:
```
bootstrapper: minikube
version: 0.25.0
K8s: 1.9.0
Networking: Calico
Container Runtime: CRI-O
```

Test go on for >1hour, then when tries to report back, get the following error (and proceeds to cleanup, which destroys the results):

```
INFO: Failed to get logs from node "minikube" pod "client-envvars-e110f82f-0472-11e8-b965-0a580a010080" container "env3cont": the server rejected our request for an unknown reason (get pods client-envvars-e110f82f-0472-11e8-b965-0a580a010080)
```

**Comment by chuckha** [comment]
If the issue is that the aggregator server is timing out but the plugins are still running there is an option to set to increase the timeout. There is an example here: https://github.com/heptio/sonobuoy/blob/master/examples/conformance.yaml#L102

If the issue is that the plugin pod is just stuck, it would be very helpful to grab the relevant logs so we can try to improve the tests upstream (if possible)

**Comment by timothysc** [comment]
I think we should gracefully terminate the e2es ahead of the timeout and rollback the data with failures...

**Comment by timothysc** [comment]
Most of the time the wedging occurs from legitimate failures that folks want to diagnose.
