### ISSUE TITLE
Example should use a Deployment instead of a Pod

### ISSUE THREAD

**Issue by luxas** [heptio/sonobuoy#22]
Nit but probably more reliable

**Comment by timothysc** [comment]
Nope, this was intended due to issues with exiting.  

Both deployments/jobs/etc do not properly perform one-shot runs, only pods do :-( 

So for better or worse this is what is has to be for now.  Ideally we wanted it to be Jobs.  

Perhaps we should use this as a means to force upstream to fix it.
