### ISSUE TITLE
kubespray: clusterapi-tester crash because of default service account

### ISSUE THREAD

**Issue by ArchiFleKs** [heptio/sonobuoy#233]
Maybe it is me but is the default service account supposed to be able to list node by default (I'm on 1.9.2).

I ran 

```
kubectl apply -f https://scanner.heptio.com/74e5213878a4183b2e4522e0525e1936/yaml/
```

```
kubectl --namespace default logs -f clusterapi-tester
                                                            
2018/02/09 08:44:19 Failed to list nodes: nodes is forbidden: User "system:serviceaccount:default:default" cannot list nodes at the cluster scope
```

**Comment by timothysc** [comment]
@ArchiFleKs - Could you describe the issue in more detail how you came about this issue?  

I'm slightly confused by what you were trying to do, and what issue you had w/sonobuoy?

**Comment by ArchiFleKs** [comment]
I ran the yaml available at https://scanner.heptio.com/ against a 1.9.2
cluster. The cluster has RBAC enable. The sononobuoy namespace is created
and everything in it. But when the the sonobuoy pods try to run e2e test it
spawn a pod in the namespace default, called cluster api tester and that
pod failed because the default service account does not as permission to
list node.

**Comment by ArchiFleKs** [comment]
And I did not make any modification to the cluster default RBAC. That’s why
I was wondering if you expect the default service account to be able to
list node and if this is supposed to be the default RBAC in kubernetes 1.9
Le lun. 12 févr. 2018 à 20:33, Kévin Lefevre <lefevre.kevin@gmail.com> a
écrit :

**Comment by timothysc** [comment]
@ArchiFleKs What tool did you use to provision your cluster?

**Comment by ArchiFleKs** [comment]
The one I tested on was kubespray. I can test on other cluster.

**Comment by timothysc** [comment]
@ArchiFleKs We test a number of different targets every release, including GKE, Azure, our Quickstart on AWS.  I've never seen this issue before.

**Comment by ArchiFleKs** [comment]
@timothysc thanks i'll retry and report a "cleaner" issue if necessary

**Comment by austinmoore-** [comment]
I'm seeing the same issue. The clusterapi-tester pod launched in the default namespace uses the default service account for that namespace, which doesn't have any permissions.

**Comment by chuckha** [comment]
I see what's going on here.

These clusters are failing this condition: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/e2e.go#L189

This is causing a pod to be created in the default namespace, which sonobuoy is not expecting, so we get RBAC errors. I guess I would expect the e2e tests to be able to create this RBAC role for itself, but it's not doing that. Maybe that's an upstream issue? We could include a default service account role so that this error state can proceed, but that feels like a work around to me

Here are some relevant links for your perusal:

https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/util.go#L603
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/e2e.go#L340
https://github.com/kubernetes/kubernetes/blob/master/test/images/clusterapi-tester/pod.yaml

I'll search for upstream issues and submit one in a bit.

**Comment by chuckha** [comment]
@austinmoore- @ArchiFleKs Would either of you be able to provide the logs from the `e2e` container in the `sonobuoy-e2e-job-<id>` pod in the `heptio-sonobuoy` namespace when this failure occurs? It looks like your e2e tests are not running as the sonobuoy service account even though it's specified in the YAML you're running.

**Comment by timothysc** [comment]
From digging this appears to be kube-spray deployment issue and not a sonobouy issue.  Sonobuoy is detecting an issue in the deployment.

**Comment by timothysc** [comment]
We'll leave this open /cc @ant31 @mattymo

**Comment by timothysc** [comment]
Closing.  Timeout + Not a sonobuoy issue.
