### ISSUE TITLE
RFE: Debug scenarios, block on failure... don't cleanup

### ISSUE THREAD

**Issue by timothysc** [heptio/sonobuoy#299]
There exist conditions where operators want to block on a failure condition and not cleanup.  

This would: 
Fail a given test and potentially block on the failed test, and not continue to other tests. 

Blocking would allow an operator or developer to then jump in to determine the cause of the failure.

**Comment by ceridwen** [comment]
The primary use-case I have for this option is network testing.  The usual symptom for broken networking is "A connection was made/failed to be made," which doesn't help debugging much because the problem could be in any component in the networking stack and any of a large number of different errors.  (The packets could be being dropped or routed elsewhere, there could be excess latency in the network such that the test's timeout is being hit, and so on.)  Logging is often insufficient to distinguish between different possible problems.  Being able to test hypotheses about what's causing the failure in the set up where the test is failing helps a lot.

**Comment by johnSchnake** [comment]
So upstream does have a method for preventing cleanup; I dont think you can tell ginkgo to pause on failure though so it would be a manual process of watching for issues and then debugging live. At least the namespaces wouldn't automatically get blown away by e2e if that was surfaced.

This would just be a matter of exposing it in the conformance image (now upstream) and then allowing that value to be set on e2e. Depending what happens on #616 that may not require further work on our part.

**Comment by johnSchnake** [comment]
Putting this on the milestone for 15.1 for the main goal of considering the cleanup logic and adding the ability to specify that a plugin (or all of them?) shouldn't be cleaned up after the run.

Not sure about the blocking on failure though; I think the implementation of that adds a lot of complexity and if we are able to get something like status notifications working, you could already get notified early about failures (it just wouldn't block entirely).
