### ISSUE TITLE
RFE: Implement progress for e2e tests

### ISSUE THREAD

**Issue by chuckha** [heptio/sonobuoy#354]
Something simple we could do is parse the e2e logs (they tell us how many things will run and when things finish). The thing could update the status metadata with some extra % information.

A more long-term solution would be to integrate something directly with ginkgo. This would be good for the extended tests as well.

**Comment by timothysc** [comment]
As a sonobuoy user, I'd like to know the overall percentage complete for each plugin.

This is hacky b/c every plugin is different, and the only contract between the worker<>plugin is the /done file.

Not all tests are the same, so for some things it will total test percentage complete.

This needs to be thought through in a generic fashion that isn't a hack.

**Comment by timothysc** [comment]
Adding as a stretch for v1.11 refresh b/c this is one of the most common things folks ask for.

**Comment by chuckha** [comment]
Here's an idea:

Plugins have a status label. We could add an optional label for plugins to use `sonobuoy.hept.io/progress`. If it exists and the status is not completed or failed, then we display whatever that value is.

Plugins could have sidecar progress updaters custom to the type of plugin that they are.

There could be somewhat generic sidecars that do things like "this plugin will take approximately <configurable number of minutes>" then the side car will update progress based on a time guess. After 2.5 minutes we'd expect a pod that takes 5 minutes to be 50%.

However, if we can use extra information about the pod to determine its status, the sidecar could do something like read the logs and update based on the updates it finds. For instance, any plugin based on ginkgo runner that uses --progress could have the same side-car that reads ginkgo --progress logs and updates status with a percentage.

**Comment by timothysc** [comment]
@chuckha lets sync with @liztio when you are around.

**Comment by timothysc** [comment]
This is the most asked for feature, but the general solution requires refactoring and the integration with ginkgo runners is also non-trivial.

**Comment by johnSchnake** [comment]
I think the way to do this with as little coupling as possible is to introduce another optional contract for the workers to follow. Just like how we use the `done` file to track a done status, I think it is reasonable to use a `status` file to emit status information.

I'm not sure if we should require the data to be structured or if we should allow random output, that way plugins and write plain text like it was a log. One option is to treat the whole file as the current status, so each time you update the status the file should get truncated and written fresh. This makes the file small, easy to manipulate, etc. However, a more general idea may be to allow appends to the file so it operates as a log where the last line/entry is the current status. This may get long and lead to lots of repeated data though (in the case of e2e tests would the status have to keep repeating total # of tests and other similar data?) I lean towards the former, simpler file. Even though it wouldn't operate as a log, it would be useful for users to poll against to get a better sense of the state of the run instead of the actual log output which is very verbose and not very informative.

For e2e specifically this is something I think we need to change upstream. We need to write _some_ data that is consumable by consumers _while_ the tests are running. The junit results, for instance, are structured for consumption but are not written until the end of the entire test run and also don't easily provide the info we want (# of tests to run, etc).

For e2e we can write a custom reporter that will emit structured data for anyone to consume in their own system. https://onsi.github.io/ginkgo/#writing-custom-reporters provides the way to do this and it is pretty straight forward and easy to get lots of data. I just made a POC to write structured data and it worked well. I could keep writing this data to a status file

**Comment by johnSchnake** [comment]
https://github.com/kubernetes/kubernetes/issues/78535

**Comment by johnSchnake** [comment]
Rather than deal with status files, after some discussions we've settled on the idea that a little webhook would be a better interface.

I've got a POC of this working locally with high level design being:
 - the sonobuoy worker (sidecar to the plugin) will run a little server just listening on localhost
 - the plugin will (optionally) emit status updates to the localhost:PORT (port specified in an env var)
 - the sonobuoy worker will take that simple status update data (e.g. 57% complete) and add some data about the plugin name/node name (so the plugin doesn't have to worry about any of that)
 - the sonobuoy worker sends that data to the aggregator pod at a new endpoint (e.g. /api/v1/status) over HTTPS (which it already knows how to do; it is the same as sending results)

The main question now (and I'd love feedback here) is what the basic `StatusUpdate` data looks like.

Some ideas:
 - % complete
 - actions done vs total actions (so we can show #s or calculate % ourselves)
 - a field to track failures/errors encountered so far `errors []string` (do we also want a `failures []string` field or is that redundant?
 - Do we want another `statusMsg string` message which would just be a human-readable string that plugins could use however they want? "Doing xyz...." "Testing xyz...", etc?
 - Do we want a generic databag type of value, e.g. `data map[string]string` which users could load with whatever they want? Maybe this instead of specific errors/failures slices? In that case errors/failures could just be special keys in that map that we document. Maybe this is more clean, maybe this is more opaque?
