### ISSUE TITLE
Unhelpful e2e output when there are no failed tests

### ISSUE THREAD

**Issue by chuckha** [heptio/sonobuoy#380]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Feature Request
**What happened**:
I ran `sonobuoy e2e results.tar.gz` and i got 

```
test salazar:tmp cha$ sonobuoy e2e 201803151919_sonobuoy_5ccc8263-716d-462e-a8a3-eb971b183d35.tar.gz 
failed tests

```
**What you expected to happen**:
I expected it to tell me that i had no failed tests or told me at least how many ran and how many failed
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Sonobuoy tarball (which contains * below)
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):

**Comment by chuckha** [comment]
Bumping this because it's come up in #sonobuoy at least once

**Comment by waynr** [comment]
I just saw this even though in the actual e2e logs text file I see:
```Ran 136 of 996 Specs in 400.117 seconds
SUCCESS! -- 136 Passed | 0 Failed | 0 Pending | 860 Skipped 

Ginkgo ran 1 suite in 6m42.660076109s
Test Suite Passed
```

**Comment by johnSchnake** [comment]
Definitely a bug that should be fixed. Maybe a great place for a more useful side tool outside of sonobuoy as well. However, since we're talking about investigating the _tar_ file itself (which sonobuoy generates) and not just the raw junit results, it makes sense for sonobuoy to do some of this work. For the time being some patch should go in to fix this though.
