### ISSUE TITLE
Docs: re-run of the test on the existing namespace does not create pods

### ISSUE THREAD

**Issue by puppet-py** [heptio/sonobuoy#42]
1. git install the sonubuoy and run the test as steps provided in the READ.md
2. If the test run fails due to network-proxy issue, it raises the GO panic trace as see from the logs of the pod created in the namesapce "heptio-sonubuoy"
3. Because of the above panic, in my understand the cleanup never gets executed, thereby the namespace "heptio-sonobuoy" persists
4. Now re-apply the yaml file (kubectl apply -f examples/quickstart/), this time the pods are not getting created. User has to delete the namespace and then re-apply the yaml.

**Comment by kensimon** [comment]
This is the case even if sonobuoy runs sucessfully... the pod stays around so that you can `kubectl cp` the output tarball locally.  In order to re-run sonobuoy you need to delete the pod (or the whole namespace) and recreate it.

Re-titling this, I think our docs need to be fixed to make this more clear.

**Comment by kensimon** [comment]
@abiogenesis-now who may be interested in updating the README here

**Comment by kensimon** [comment]
Closing this since we have more clarity in the docs now
