### ISSUE TITLE
Option for non-systemd distro

### ISSUE THREAD

**Issue by andrewrynhard** [heptio/sonobuoy#508]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
`systemd_logs` plugin fails

**What did you expect to happen:**
I don't know what to expect, but requiring `systemd_logs` will never work for the project I am working on, because systemd is not used.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
```
$ kubectl logs sonobuoy-systemd-logs-daemon-set-49a533f5cc6e423a-pnjcm -n heptio-sonobuoy -c sonobuoy-systemd-logs-config
chroot: failed to run command 'journalctl': No such file or directory
```

**Environment:**

- Sonobuoy version: 
```
$ sonobuoy version
v0.11.4
```
- Kubernetes version: (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0-dirty", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"dirty", BuildDate:"2018-07-14T04:41:14Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version:
kubeadm
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): 
https://github.com/autonomy/talos
- Sonobuoy tarball (which contains * below)

**Comment by timothysc** [comment]
Hey @andrewrynhard it's really easy to disable in the config, but we can also do an extra bit of autodetection. 

To override run `sonobuoy gen` and you can disable remove the plugin from the config.  If you want total control there is a client interface (https://github.com/heptio/sonobuoy/blob/master/pkg/client/interfaces.go) which gives folks complete control.

**Comment by stevesloka** [comment]
Hey, @andrewrynhard I think the issue here is `sonobuoy run` isn't very user-friendly to allow you to customize the plugins you would like to enable for a run. Today you'd have to customize the output using `sonobuoy gen` first (like @timothysc mentioned) but we'd like to make this process better. 

Also related to #405

**Comment by tsal** [comment]
This seems to be impacting `jx compliance run` for jenkins-x; I'm not sure if that should be a separate issue over there, or this is the appropriate place.

**Comment by johnSchnake** [comment]
@tsal do you have a link to show the issue you're talking about? If it is the same issue then no reason to create another; but it would be good to have the example impact.

**Comment by johnSchnake** [comment]
Marked this for the 0.14.2 milestone but basing that on the understanding that the fix is simply to make it easier to _not_ run the plugin.

Currently https://github.com/heptio/sonobuoy/pull/683 will enable you to do something like ```sonobuoy run --plugin e2e``` which will make the sytemd-logs plugin not run/error.

Going to go ahead and close this with the understanding that since I am considering that the fix, then this becomes just a duplicate issue to #405 .
