### ISSUE TITLE
Endpoint for reporting status of running scan.

### ISSUE THREAD

**Issue by wilreichert** [heptio/sonobuoy#51]
Sort of in line with whats discussed in #49 

It would be useful if there was a REST endpoint that
1. provided the current global state, eg. RUNNING, COMPLETED
2. provided the current state of an individual plugin, e.g. WAITING, RUNNING, COMPLETED (PASS/FAIL)
3. provided the ability to pull the data/logs associated with individual plugins

**Comment by timothysc** [comment]
We've had a couple of requests for this, but we're not entirely sure on the interface & semantics that make the most sense.

**Comment by jrnt30** [comment]
One naive approach to this may be to simply have a sidecar running on the master, as it is centralizing the results instead of baking this into Sonobuoy proper.  There could be a number of integrations that may be useful (web hooks, slack notification, rest api for scraping, shipping results to s3, etc.) that could intuit some of this information by polling the shared results folder (almost exactly the same as the producer/consumer architecture for the plugins themselves). 

A much larger effort architecturally could be to expose the results of as a CRD similar to the heptio/ark which then allows watches on the results, etc. and implementing the notifier system through a more decentralized process.

**Comment by timothysc** [comment]
Yup we conversed about this approach internally.   
Except sonobuoy is the sidecar in this case.

**Comment by liztio** [comment]
You can now query the state of a sonobuoy run by looking at the `sonobuoy.hept.io/status` annotation on the master pod. Full writeup is at https://github.com/heptio/sonobuoy/blob/master/docs/enhancements/status-reporting.md
