### ISSUE TITLE
Cleanup service accounts after a run.

### ISSUE THREAD

**Issue by jayunit100** [heptio/sonobuoy#532]
**What steps did you take and what happened:**
Ran sonubuoy, cleanup occured of NS, but svc accounts lingered.

**What did you expect to happen:**
delete all heptio svc account artifacts created, or alternatively, leave everything in place.

**Anything else you would like to add:**
I use scanner.heptio.com...
- it would be nice if maybe we actually kept the namespace around, because we could go look up the URL again if we lost it, for where it was sending the test data to.
- if we dont keep the NS, we prob should also kill off all the svc accounts as well , b/c it can Be confusing.

Huge Thanks again to the heptio folks for this awesome tool + the hosted web ui, it makes running the e2e tests a daily occurence as opposed to a last resort :) !

**Comment by stevesloka** [comment]
The service account is namespace scoped and should be deleted when the namespace is deleted. What I think hangs around are the ClusterRole and corresponding ClusterRoleBinding that we should delete. 

Those need to be cluster scoped since Sonobuoy looks across all namespaces. Let me open an issue in the namespace delete repo (https://github.com/heptiolabs/namespace-deleter) and see if I can add this functionality.

**Comment by johnSchnake** [comment]
Closing; the Scanner is no longer supported at this time. Thank you for your interest in that project. If you have other Sonobuoy questions or issues please feel free to reach out.
