### ISSUE TITLE
Allow sonobuoy plugins to have custom annotations

### ISSUE THREAD

**Issue by jeffb4** [heptio/sonobuoy#567]
**Describe the solution you'd like**
I would like to be able to specify custom annotations for sonobuoy plugin pods

**Anything else you would like to add:**
Particularly I am creating a sonobuoy plugin based on powerfulseal, and in that vein I need to add kiam annotations to the powerfulseal pod. Instead of doing a 2-stage launch (launching powerfulseal pod /w annotation from the plugin pod) it would be far easier to specify the annotation into the plugin config yaml.

**Environment:**

- Sonobuoy version: 0.11.6
- Kubernetes version: (use `kubectl version`): 1.10
- Kubernetes installer & version: bootkube
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): CoreOS

**Comment by timothysc** [comment]
Currently, we leverage annotations on pods in the worker process to allow to report overall status.  It's possible to enable a custom override via the plugin definition, but as of today, they would collide.  

Happy to enqueue, but I'm not certain we will have time soon to address.

**Comment by jeffb4** [comment]
How would a custom override work in the plugin definition? While I think it's a worthwhile feature for the backlog, any workaround (including supplying my own completely generated pod definition for the worker pod) would be fine by me.

**Comment by johnSchnake** [comment]
@jeffb4 So is it that you just want to be able to specify an annotation that you want set on the worker at startup?

I think that what @timothysc is saying is that when you specify the yaml for your plugin you can specify annotations as needed just like usual.

Maybe I'm not understanding what your optimal solution looks like? Are you looking for a CLI integration specifically?

**Comment by jeffb4** [comment]
That is exactly what I need to do. In my plugin definition, I need to add an annotation that kiam can pick up. The plugin definition YAML doesn't support annotations (or didn't as of December 2018) on plugin pods.

**Comment by johnSchnake** [comment]
From our conversation in slack things have gotten much more clear. The issue, as you pointed out, s that the values you are placing in the YAML dont survive once the `sonobuoy master` loads the config because the config type doesnt have that value to unmarshal into. In addition, adding it to the config will only be half the problem because the workers are made from another template which that config is loaded into.

So the fix is 2 parts:
 - add the fields in the config
 - add the extra template in the worker/daemonset to use this

The latter point there is what users today have no say over since it is stored/generated from the code after everything is in flight.

**Comment by johnSchnake** [comment]
#660 did this with imagePullSecrets. This should be even easier to accomplish since (1) it only affects the plugins (2) it can be validated with simple images/registries and (3) doesnt require any manual steps like creating secrets in the namespace

**Comment by johnSchnake** [comment]
@jeffb4 Would providing the annotations on a global scale satisfy your needs or for you does it need to be per-plugin?

The reason I ask is that if there are kiam permissions that plugins need it seems like the aggregator would need them as well (in order to get all the data queries to work). If I were to integrate it as a per-plugin option you'd have to adjust each plugin and manually modify the main yaml from `sonobuoy gen` as well.

Alternatively, the option I'm promoting, if I add an option to the config file to track these custom annotations, they can be placed on the aggregator pod and all the plugins with a single config option.  Would that work for your use case?

**Comment by jeffb4** [comment]
For my use case I did not need the annotations to be global - the sonobuoy plugin pod needed the annotation (for powerfulseal to do some EC2 scanning) but it wasn't needed in the aggregator, for instance. That said it also would be usable if it was global, if that is a significantly easier change for instance.

**Comment by jeffb4** [comment]
@johnSchnake - thanks for all your work getting this in!
