### ISSUE TITLE
reports failure when 0 test cases failed

### ISSUE THREAD

**Issue by elizanp** [heptio/sonobuoy#569]
**What steps did you take and what happened:**
Ran sonobuoy e2e tests

**What did you expect to happen:**
When there are no failed test cases, expect the test suite to report SUCCESS
Instead k8s_e2e.log reported this
FAIL! -- 213 Passed | 0 Failed | 0 Pending | 1499 Skipped

**Anything else you would like to add:**
--

**Environment:**
Redhat VMs

- Sonobuoy version: 0.12.0
- Kubernetes version: (use `kubectl version`): 
kubernetes version: v1.12.3-1+fee411aca93f0e | kubectl Client Version: v1.12.2

- Kubernetes installer & version: Kubernetes 1.12.3
- Cloud provider or hardware configuration: RHEL 7.5
- OS (e.g. from `/etc/os-release`):
- Sonobuoy tarball (which contains * below)
 sonobuoy_0.12.0_linux_amd64.tar.gz

[k8s_e2e.log](https://github.com/heptio/sonobuoy/files/2673081/k8s_e2e.log)

**Comment by timothysc** [comment]
@elizanp if you have the complete tarball I can use it to diagnose what the issue is.

**Comment by elizanp** [comment]
@timothysc  I'm afraid the tarball is not longer around for debugging.

**Comment by johnSchnake** [comment]
Its been a while since I've had this but I've had something similar.

In my case the problem was a timeout. I peeked at the k8s code printing that failure line and it is based off of a field: `SuiteSucceeded` which gets set in certain circumstances. I think there is a timeout occurring such that the suite stops running (doesnt fail a specific test) but doesn't report that the suite succeeded.

In my situation it was a sonobuoy default timeout that needed bumped which you can do through the sonobuoy config file.

Upon doing this we actually found that for some times we had _thought_ we were seeing a few flakey tests, but in reality we were getting a timeout and so we'd only _sometimes_ be running a few tests which were actually always failing.

You'll just have to look carefully in your logs the next time this happens to see if you can see any language about timeouts. In our case, it was not at the end of any logs, but in the middle of the sonobuoy logs since there was still cleanup/reporting that followed.

You could also carefully look at the list of tests that got reported as having been run and compare that against the set of tests you _thought_ should be running.

Without logs to look at there isn't anything else I can do to help. If it happens again let us know.
