### ISSUE TITLE
Cannot run tests with tainted nodes using tolerations

### ISSUE THREAD

**Issue by ElectricRabbit** [heptio/sonobuoy#571]
I was able to configure master POD to use tolerations, but I didn't find way how to edit config.json configmap like this:

apiVersion: v1
data:
  config.json: |
    {
      "Description": "sonobuoy run for scanner.heptio.com",
      "Version": "v0.13.0",
      "ResultsDir": "/tmp/sonobuoy",
      "Resources": [
        "Nodes",
        "ServerVersion"
      ],
      "Filters": {
        "Namespaces": ".*",
        "LabelSelector": ""
      },
      "Server": {
        "bindaddress":"0.0.0.0",
        "bindport":8080,
        "advertiseaddress":"",
        "timeoutseconds":8000
      },
      "Plugins": [
        {
          "name":"e2e"
        }
      ],
      "WorkerImage":"gcr.io/heptio-images/sonobuoy:v0.13",
      "ImagePullPolicy":"Always",
      "Tolerations": [
        {
          "key":"dedicated",
          "operator":"Exists",
          "effect":"NoSchedule"
        }
      ]
    }
kind: ConfigMap
metadata:
  labels:
    component: sonobuoy
  name: sonobuoy-config-cm
  namespace: heptio-sonobuoy

to use tolerations for worker(job) pods, without luck, I guess master cannot work with this parameter. We tried to untaint one node for this purpose, job was created, but it timed out soon waiting for other schedulable nodes:

/usr/local/bin/ginkgo --focus=\[Conformance\] --skip=Alpha|\[(Disruptive|Feature:[^\]]+|Flaky)\] --noColor=true --nodes=1 /usr/local/bin/e2e.test -- --disable-log-dump --repo-root=/kubernetes --provider="local" --report-dir="/tmp/results" --kubeconfig=""
I0122 11:33:01.884851      18 test_context.go:358] Using a temporary kubeconfig file from in-cluster config : /tmp/kubeconfig-344105714
I0122 11:33:01.884966      18 e2e.go:224] Starting e2e run "79b0c024-1e39-11e9-bbc9-0a580a0c0d28" on Ginkgo node 1
Running Suite: Kubernetes e2e suite
Random Seed: 1548156781 - Will randomize all specs
Will run 201 of 1946 specs
 Jan 22 11:33:01.986: INFO: >>> kubeConfig: /tmp/kubeconfig-344105714
Jan 22 11:33:01.988: INFO: Waiting up to 30m0s for all (but 0) nodes to be schedulable

Is there some way how to run sonobuoy test with tainted nodes?

**Comment by johnSchnake** [comment]
Based on my reading of your ticket it seems like you have one node which is marked as unschedulable. Even if you in theory got the pod running the plugin (e2e plugin + sonobuoy worker) to tolerate that, the e2e tests themselves actually run numerous pods which would then have issues so that approach is a deadend.

Is my understanding correct? The unschedulable taint is only permitted (via the tests) on the nodes marked as masters. Please let me know if my understanding was off or if there is some reason why you can't get the master untainted.

You only get into problems when you have unscheduable nodes which are not marked as master as mentioned here: https://github.com/heptio/sonobuoy/issues/507

The discussion around that ticket was simply that larger upstream plumbing would have to be done if it wanted to be supported but after doing some searching I'm not sure how likely that is since the taints/tolerations seems to be sprinkled throughout the codebase in templates and in code.

Since we do get this sort of question fairly frequently, I've opened an upstream ticket so that sig-testing can weigh in on the potential of it being supported in the future. See https://github.com/kubernetes/kubernetes/issues/74282
