### ISSUE TITLE
Sonobuoy wont run with node that's not a worker

### ISSUE THREAD

**Issue by hoeghh** [heptio/sonobuoy#574]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I provisioned a cluster with RKE with a master (etcd, controlplane) and some worker nodes. The master has no worker roles. Then run sonobuoy, and it hangs.

```
NAME              STATUS   ROLES               AGE   VERSION
192.168.122.111   Ready    controlplane,etcd   17m   v1.12.5
192.168.122.112   Ready    worker              17m   v1.12.5
192.168.122.113   Ready    worker              17m   v1.12.5
192.168.122.114   Ready    worker              17m   v1.12.5
192.168.122.115   Ready    worker              17m   v1.12.5
```
**What did you expect to happen:**
Sonobuoy would start running tests

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Error from Sonobuoy 
```
kubectl logs sonobuoy-e2e-job-e47ad0f27edd4cf7 -n heptio-sonobuoy -c e2e
/usr/local/bin/ginkgo --focus=\[Conformance\] --skip=Alpha|\[(Disruptive|Feature:[^\]]+|Flaky)\] --noColor=true --nodes=1 /usr/local/bin/e2e.test -- --disable-log-dump --repo-root=/kubernetes --provider="local" --report-dir="/tmp/results" --kubeconfig=""
I0129 13:17:08.932855      14 test_context.go:358] Using a temporary kubeconfig file from in-cluster config : /tmp/kubeconfig-376065014
I0129 13:17:08.933065      14 e2e.go:224] Starting e2e run "2df20e66-23c8-11e9-b7db-0a580a2a0004" on Ginkgo node 1
Running Suite: Kubernetes e2e suite
===================================
Random Seed: 1548767828 - Will randomize all specs
Will run 201 of 1946 specs
Jan 29 13:17:09.116: INFO: >>> kubeConfig: /tmp/kubeconfig-376065014
Jan 29 13:17:09.120: INFO: Waiting up to 30m0s for all (but 0) nodes to be schedulable
```

**Environment:**

- Sonobuoy version: From website
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.5", GitCommit:"51dd616cdd25d6ee22c83a858773b607328a18ec", GitTreeState:"clean", BuildDate:"2019-01-16T18:14:49Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version:
RKE from Rancher v0.2.0-rc4
- Cloud provider or hardware configuration: VM's on laptop
- OS (e.g. from `/etc/os-release`): CentOS Linux release 7.5.1804 (Core) 
- Sonobuoy tarball (which contains * below)

-------------------------------------------
If i create the cluster with worker roles on all nodes, Sonobuoy starts its tests. So, Sonobuoy seems to wait for a non-worker node to be schedulable, which doesn't make sense.

**Comment by johnSchnake** [comment]
So this part of the code isn't actually within sonobuoy, it is within the k8s testing code itself. It does allow master nodes to not be schedulable but there is some specific logic about tags/labels/taints.

See: https://github.com/kubernetes/kubernetes/blob/8b98e802eddb9f478ff7d991a2f72f60c165388a/test/e2e/framework/util.go#L2726-L2756

It may be that the installer should just be marking the nodes differently in order to be more in line with convention and testing expectations.

**Comment by fsanys** [comment]
Hello @hoeghh,
As a workaround you can cordon the master nodes to be able to run the tests.
Hope it can help you.

**Comment by johnSchnake** [comment]
Yes, so after looking at the rancher code and the info you gave, it just seems like RKE marks the master node with a `controlplane` label instead of a master label. You could either 
1) file a ticket with RKE to add/change their label in order to get e2e tests to run correctly
2) Try and file an upstream ticket with k8s to modify their logic w.r.t. the master label
3) Ensure that you allow workloads to run on your control plane node
