### ISSUE TITLE
Use upstream conformance image 

### ISSUE THREAD

**Issue by timothysc** [heptio/sonobuoy#593]
**Describe the solution you'd like**
Use upstream image for tests, vs. downstream image. 

**Anything else you would like to add:**
Verify that the image is produced for 1.14/1.13, and 1.12 for a 1.14 release. 

/cc @stevesloka @johnSchnake

**Comment by johnSchnake** [comment]
Thats fantastic; I didn't realize that issue got resolved. For other's context, k8s upstreamed our image/script effectively and supports it now. https://github.com/kubernetes/kubernetes/tree/9c5cf3ccf77225fd38772a5a9162d6dc7f818d20/cluster/images/conformance

**Comment by stevesloka** [comment]
Also, may be able to deprecate: https://github.com/heptio/kube-conformance once this change happens.

**Comment by johnSchnake** [comment]
Punting this to 1.15 because the upstream image is so new it hasn't been part of a release yet, limiting our ability to test the integration well.

In the meantime I'll be able to update our kube-conformance image to include dryRun support just like the upstream just did.

**Comment by johnSchnake** [comment]
Actually what we were told was a mistake and they've been publishing these since v1.13:
https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/conformance?gcrImageListsize=30&gcrImageListquery=%255B%255D

e.g. gcr.io/google-containers/conformance:v1.13.0

Moving back to v0.14 and putting up a PR.
