### ISSUE TITLE
hostAlias test fails when hostAliases can be created

### ISSUE THREAD

**Issue by dvdmuckle** [heptio/sonobuoy#648]
**What steps did you take and what happened:**
After running the Sonobuoy scanner (https://scanner.heptio.com) on an AWS cluster with K8s v1.11.9, we passed every conformance test except for the ability to create hostAliases. However, creating a pod/deploy with a hostAliases field worked as expected.

**What did you expect to happen:**
All conformance tests, including hostAlias, to pass.

**Anything else you would like to add:**
Log from scanner of the particular failed conformance test
```
/workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:699
Timed out after 60.000s.
Expected
    <*errors.errorString | 0xc000b53350>: {
        s: "expected hosts file to contain entries from HostAliases. Got:\n# Kubernetes-managed hosts file.\n127.0.0.1\tlocalhost\n::1\tlocalhost ip6-localhost ip6-loopback\nfe00::0\tip6-localnet\nfe00::0\tip6-mcastprefix\nfe00::1\tip6-allnodes\nfe00::2\tip6-allrouters\n[REDACTED_IP]\tbusybox-host-aliasesaliases9939ca20-50ba-11e9-9945-4aecb9c4c94c\n\n# Entries added by HostAliases.\n123.45.67.89\tfoo\n123.45.67.89\tbar\n",
    }
to be nil
/workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/kubelet.go:183
```

**Environment:**

- Sonobuoy version: scanner.heptio.com
- Kubernetes version: (use `kubectl version`): 1.11.9
- Kubernetes installer & version: Kops 1.11.1
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`):  Debian Stretch
- Sonobuoy tarball (which contains * below): N/A

**Comment by johnSchnake** [comment]
The fact that this just fails a particular test points to either a potential problem in the test or your configuration.

I would recommend filing this bug against kubernetes/kubernetes with the `/area conformance` since it is a conformance test. Someone more familiar with the hostAlias features may be able to help you.

One note would be that at this point your version is pretty out of date though and I'm not sure that they  would investigate more without first having you upgrade (I dont know if much dev has happened around that feature or tests). The best information I can find indicates 3 minor releases is supported and with the release of 1.14, that means that 1.11 isnt any more.

In any case, the fact that you were able to run the scan, get the results, and the plugins were able to run indicates that the bug doesn't reside in Sonobuoy.

Sorry I can't help further.
