### ISSUE TITLE
Sonobuoy shows "failed tests" but doesn't show which test failed.

### ISSUE THREAD

**Issue by arpitairan** [heptio/sonobuoy#690]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

0. Install sonobuoy binary directly to /usr/local/bin
1. sonobuoy run
2. sonobuoy status 
(Once the tests are complete)
3. sonobuoy retrieve .
4. sonobuoy e2e bundle.tar.gz

Output - 
$ sonobuoy e2e bundle.tar.gz
failed tests

$

**What did you expect to happen:**

$ sonobuoy e2e bundle.tar.gz
failed tests
- list of the failed tests.

$

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

1. sonobuoy logs 
No ERROR logs, only INFO level logs

**Environment:**

- Sonobuoy version: 0.13.0
- Kubernetes version: (use `kubectl version`): 1.11.9
- Kubernetes installer & version: Kops 1.11.1
- Cloud provider or hardware configuration: AWS Cloud
- OS (e.g. from `/etc/os-release`):  VERSION="18.04.1 LTS (Bionic Beaver)
- Sonobuoy tarball (which contains * below)

**Question:**
1) Does sonobuoy needs to run resources on master node in Kubernetes?
2) Does sonobuoy makes use of AWS Metadata API because we don't allow pods to access AWS Metadata API directly?

Please let me know if more information is required.

**Comment by johnSchnake** [comment]
So the most likely result is that you actually had no failed tests. See the fix here: https://github.com/heptio/sonobuoy/pull/589 and its associated issue. It went into the 0.14.0 version, so just after the version you had.

Also, there was a follow-up https://github.com/heptio/sonobuoy/pull/658 which ensured that if the plugin was missing entirely the `e2e` command would error as expected.

With regards to your questions:
> Does sonobuoy needs to run resources on the master node in Kubernetes?

No

> Does sonobuoy make use of AWS Metadata API because we don't allow pods to access AWS Metadata API directly?

No, provider-specific information is not utilized by Sonobuoy. There are multiple tests in the Kubernetes test suite that may utilize information like that but I don't believe any `Conformance` test would fall into that category.

Going to close since it seems like that fully explains your situation. Feel free to reopen/follow up if needed though. Thanks for the inquiries.
