### ISSUE TITLE
CI failures due to invalid pid value/wait logic in conformance image

### ISSUE THREAD

**Issue by johnSchnake** [heptio/sonobuoy#746]
**What steps did you take and what happened:**
Travis is often failing with:
```
ERRO[0000] could not get tests from archive: failed to find results file "plugins/e2e/results/junit_01.xml" in archive 
The command "./travis-ci.sh" exited with 1.
```
but we have 0 artifacts or extra messages to help debug this. Usually a `rerun` will fix it so the code isn't actually broken. I suspect it is a problem with the agent itself being properly sized to run the kind cluster and get the results predictably. Needs some investigation though, #744 would help tremendously.

**Comment by johnSchnake** [comment]
During our last release, this happened 2-3 times in a row; I added some debug lines and then it went green so I didn't get to check on the issue.

We need to monitor CI for these and see if the new dump of data will provide info as to why the failures are happening.

**Comment by johnSchnake** [comment]
One example here: https://travis-ci.org/heptio/sonobuoy/builds/547854573

The debug lines partially worked (and partially failed, see #761 ). In this case we could see that the e2e.log was there but not the junit.

The implication there is that it may have been the case that the run failed to execute properly at all (if that happens the junit reporter does not get run and doesnt spit out the junit file). Either that or it is a case where the results are not getting reported/saved properly.

Either way, those debug lines are starting to prove useful.

**Comment by johnSchnake** [comment]
Finally added enough/the right debug lines to figure out the flakiness in some of our CI (and the good news is that it is a known issue and an upstream issue, not our fault :slightly_smiling_face: )
https://travis-ci.org/heptio/sonobuoy/builds/548216979#L4065

See: kubernetes/kubernetes#78699

**Comment by johnSchnake** [comment]
Log lines so they get persisted here if the build gets archived.
```
Printing file info and contents of results/podlogs/heptio-sonobuoy/sonobuoy-e2e-job-6779aa36e7924ed1/logs/e2e.txt
-rw-r--r-- 1 travis travis 362 Jun 20 14:40 results/podlogs/heptio-sonobuoy/sonobuoy-e2e-job-6779aa36e7924ed1/logs/e2e.txt
+ set +x
+ tee /tmp/results/e2e.log
/run_e2e.sh: line 65: wait: `': not a pid or valid job spec
```

**Comment by johnSchnake** [comment]
The go-runner has been merged upstream and will be available starting in v1.16 of k8s. At that time I propose that we move towards using it for our CI runs at least to kick the tires.

**Comment by erikwilson** [comment]
For reference, the failing line: https://github.com/kubernetes/kubernetes/blob/4fec7c75689efb349f6809420c46554144a69c69/cluster/images/conformance/run_e2e.sh#L65

We are experiencing this with k3s also, where we are always passing the tests, but sometimes a run will fail w/o logs. I have added some extra logic to retry under certain conditions, but sometimes the run will fail too late for us to retry.

For what it is worth I am trying to understand why `run_e2e.sh` is doing a `wait "$(pgrep ginkgo)"` instead of just `wait`. If the ginko process has exited by the time we reach that line then `wait ""` will fail and that error will appear.

**Comment by erikwilson** [comment]
Thanks for filing this & the related kubernetes isssue @johnSchnake!

Submitted PR for fix, in my case I think sonobuoy is failing fast, and I clean up with `sonobuoy delete --wait` which can take a long (400s or more), I suspect because the tests are still actually running. Often I see no particularly helpful error messages, although I have seen `/run_e2e.sh: line 65: wait: `': not a pid or valid job spec` in logs. Tested the change with 100% success rate, reverted back and had 66% success rate.

**Comment by johnSchnake** [comment]
@erikwilson Thanks for your upstream change!

Good to know that even without action we should see that issue go away. I think we may (at v0.16.0 try out using the go-runner so that we can tinker with different deployment options. I do hope your change gets cherry-picked for other versions though.

**Comment by BenTheElder** [comment]
FYI I run into this locally on a reasonably powerful workstation, so I don't think it's a matter of sizing (?)

I eventually gave up on using sonobuoy for v1.15, but thankfully we had the upstream conformance image CI results (thanks for helping maintain those!) at https://testgrid.k8s.io/conformance-kind#conformance-image,%201.15%20(dev) so I've submitted those. https://github.com/cncf/k8s-conformance/pull/907

For v1.16 sonobuoy worked fine :-)
