### ISSUE TITLE
Create an interface library for decoding tarball

### ISSUE THREAD

**Issue by timothysc** [heptio/sonobuoy#97]
To reduce the friction of automation we should move to have some utility interface library that can be used by other tools to tease apart details of the tarball.  

There have been multiple requests for docs on this.  

/cc @chuckha

**Comment by chuckha** [comment]
I'm thinking about developing something like this:

```go
// Load the tarball and populate all the sub structs
client, err := tarball.NewClient(reader)

// Get the plugin data for the e2e plugin
e2e, err := client.Plugin("e2e")
if err != nil {
	panic(err)
}

// This sections shows Results exposes everything the e2e.xml file exposes.
passedTestCount := 0
failedTestCount := 0
for _, testCase := range e2e.Results.Tests {
	if testCase.Failure != "" {
		failedTestCount++
	} else {
		passedTestCount++
	}
}

// Get results not found in a plugin
k8sVersion := client.Version()
nodes := client.Nodes()
for _, node := range nodes {
	fmt.Println(node.Name)
}
```

There are a couple of important things to note:

* The client exposes the data as structs we define in this repo. That means users are limited to the implementations here. I think this will be a good user experience until they can't get something because we don't expose it or our documentation is not up to snuff.

* The client API reflects the tar directory structure. I think it's a fairly logical layout.

* We don't have to worry about the actual layout of the tarball structure. The client will manage that detail.

**Comment by timothysc** [comment]
Shifting back priority on this one, due to other objectives.

**Comment by timothysc** [comment]
I'm going to punt this out till next cycle.  Important, but not urgent.

**Comment by timothysc** [comment]
Let's spec this one out in more detail together.
